name: ansible-lint
on:
  workflow_call:
    inputs:
      ansible_lint_version:
        description: The version of ansible-lint to run.
        required: false
        type: string
        default: "main"

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ansible-network/github_actions/.github/actions/checkout_dependency@main

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@"${{ inputs.ansible_lint_version }}"
