name: Ensure Backporting
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  labelling:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'mergeit') && !contains(github.event.pull_request.labels.*.name, 'do_not_backport') }}
    steps:
      - uses: ansible-network/github_actions/.github/actions/ensure_backporting@main
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN  }}
