name: tagging

on:
  workflow_call:
    inputs:
      branch_name:
        description: The branch name to create tag from.
        type: string
        default: ${{ github.base_ref }}
      release_publish:
        default: true
        description: Publish a new github release.
        type: boolean
      release_prefix:
        default: "Release"
        description: Prefix name of the release to create.
        type: string
    secrets:
      # due to https://github.com/ad-m/github-push-action/issues/32 we are not using default GITHUB_TOKEN
      gh_token:
        required: true

jobs:
  push:
    if: ${{ github.event.pull_request.merged == true }} and ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-tag') }}
    runs-on: ubuntu-latest
    env:
      GH_BRANCH: ${{ inputs.branch_name }}
      GH_TOKEN: ${{ secrets.gh_token }}
      GH_PUBLISH_RELEASE: ${{ inputs.release_prefix }}
      GH_RELEASE_PREFIX: ${{ inputs.release_prefix }}}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GH_BRANCH }}
          token: ${{ env.GH_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install python libraries
        run: pip3 install yq pygithub
        shell: bash

      - name: extract tag name from 'galaxy.yml'
        id: read-tag
        run: echo "release_tag=$(yq -r '.version' 'galaxy.yml')" >> $GITHUB_OUTPUT
        shell: bash

      - name: create and push tag to Github repository
        id: push-tag
        run: |
          # git tag ${RELEASE_TAG}
          # git push origin ${RELEASE_TAG}
          # read repository default branch
          GIT_DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
          echo "default_branch=$GIT_DEFAULT_BRANCH" >> $GITHUB_OUTPUT
        shell: bash
        env:
          RELEASE_TAG: ${{ steps.read-tag.outputs.release_tag }}
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}

      - name: Create Pull Request from Release branch to default branch
        uses: ansible-network/github_actions/.github/actions/create_pullrequest@main
        with:
          token: ${{ env.GH_TOKEN }}
          repository: ${{ github.repository }}
          base_branch: ${{ steps.push-tag.outputs.default_branch }}
          head_branch: ${{ env.GH_BRANCH }}
          title: "Push changes for release '${{ steps.read-tag.outputs.release_tag }}' on '${{ steps.push-tag.outputs.default_branch }}' branch"
          body: "Automatic changes for Release ${{ steps.read-tag.outputs.release_tag }} on Repository default branch"

      # - name: Parse release content
      #   run: |
      #     curl -o create_github_release.py https://raw.githubusercontent.com/ansible-network/github_actions/main/scripts/create_github_release.py
      #     python3 ./create_github_release.py --repository ${{ github.repository }} --release-tag ${{ steps.read-tag.outputs.release_tag }} --release-name "${{ env.GH_RELEASE_PREFIX }} ${{ steps.read-tag.outputs.release_tag }}"
      #   env:
      #     GITHUB_TOKEN: ${{ env.GH_TOKEN }}
      #   if: ${{ env.GH_PUBLISH_RELEASE }}
